env:
  es2021: true
  node: true
extends:
  - standard
  - plugin:mocha/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - mocha
rules:
  semi:
    - error
    - always
  quotes:
    - error
    - single
  indent:
    - error
    - 4
